# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven


name: E2E Regression Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  schedule:
    - cron: '00 4 * * *'
  workflow_dispatch:

env:
  TESTING_SCOPE: ".*"  # Updated to cover all tests and classes

jobs:
  E2E_Chrome_Linux_Test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.6
      - name: Run Tests
        continue-on-error: true
        run: mvn test -DtargetBrowserName="chrome" -DexecutionAddress="local" -DtargetOperatingSystem="LINUX" -DheadlessExecution="true" -DwhenToTakePageSourceSnapshot="FailuresOnly" -DscreenshotParams_whenToTakeAScreenshot="FailuresOnly" -Dtest="${{ env.TESTING_SCOPE }}"
      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Chrome_Linux_Allure
          path: "target/allure-results/*"
      - name: Upload Execution Summary Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Chrome_Linux_Summary
          path: "reports/*"

  E2E_Firefox_Linux_Test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.6
      - name: Run Tests
        continue-on-error: true
        run: mvn test -DtargetBrowserName="firefox" -DexecutionAddress="local" -DtargetOperatingSystem="LINUX" -DheadlessExecution="true" -DwhenToTakePageSourceSnapshot="FailuresOnly" -DscreenshotParams_whenToTakeAScreenshot="FailuresOnly" -Dtest="${{ env.TESTING_SCOPE }}"
      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Firefox_Linux_Allure
          path: "target/allure-results/*"
      - name: Upload Execution Summary Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Firefox_Linux_Summary
          path: "reports/*"

  E2E_Edge_Windows_Test:
    runs-on: windows-latest
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.6
      - name: Run Tests
        continue-on-error: true
        run: mvn test -DtargetBrowserName="microsoftedge" -DexecutionAddress="local" -DtargetOperatingSystem="WINDOWS" -DheadlessExecution="true" -DwhenToTakePageSourceSnapshot="FailuresOnly" -DscreenshotParams_whenToTakeAScreenshot="FailuresOnly" -Dtest="${{ env.TESTING_SCOPE }}"
      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Edge_Windows_Allure
          path: "target/allure-results/*"
      - name: Upload Execution Summary Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Edge_Windows_Summary
          path: "reports/*"

  E2E_Safari_MacOS_Test:
    runs-on: macos-latest
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.6
      - name: Run Tests
        continue-on-error: true
        run: mvn test -DtargetBrowserName="safari" -DexecutionAddress="local" -DtargetOperatingSystem="MAC" -DheadlessExecution="true" -DwhenToTakePageSourceSnapshot="FailuresOnly" -DscreenshotParams_whenToTakeAScreenshot="FailuresOnly" -Dtest="${{ env.TESTING_SCOPE }}"
      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Safari_MacOS_Allure
          path: "target/allure-results/*"
      - name: Upload Execution Summary Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Safari_MacOS_Summary
          path: "reports/*"

# Optional: Add additional jobs for other browsers/platforms as needed.
