# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven


name: E2E Regression Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  schedule:
    - cron: '00 4 * * *'
  workflow_dispatch:

env:
  TESTING_SCOPE: ".*"  # Updated to cover all tests and classes

jobs:
  E2E_Chrome_Linux_Test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: maven
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.4
      - name: Run Tests
        continue-on-error: true
        run: mvn clean test --file pom.xml
      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Chrome_Linux_Allure
          path: "target/allure-results/*"
      - name: Upload Execution Summary Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Chrome_Linux_Summary
          path: "target/*"
      - name: Upload Extent Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Extent_Report
          path: reports/ExtentReports/ExtentReports.html
      - name: Publish Test Results
        continue-on-error: true
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: "Tests Results Chrome_Linux"
          files: |
            target/surefire-reports/TEST-*.xml
  E2E_Firefox_Linux_Test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: maven
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.4
      - name: Run Tests
        continue-on-error: true
        run: mvn clean test --file pom.xml
      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Firefox_Linux_Allure
          path: "target/allure-results/*"
      - name: Upload Execution Summary Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Firefox_Linux_Summary
          path: "target/*"
      - name: Upload Extent Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Extent_Report
          path: reports/ExtentReports/ExtentReports.html
      - name: Publish Test Results
        continue-on-error: true
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: "Tests Results Firefox_Linux"
          files: |
            target/surefire-reports/TEST-*.xml
  E2E_Edge_Windows_Test:
    runs-on: windows-latest
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: maven
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.4
      - name: Run Tests
        continue-on-error: true
        run: mvn clean test --file pom.xml
      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Edge_Windows_Allure
          path: "target/allure-results/*"
      - name: Upload Execution Summary Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Edge_Windows_Summary
          path: "target/*"
      - name: Upload Extent Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Extent_Report
          path: reports/ExtentReports/ExtentReports.html
      - name: Publish Test Results
        continue-on-error: true
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always()
        with:
            check_name: "Tests Results Edge_Windows"
            files: |
                target/surefire-reports/TEST-*.xml
  E2E_Safari_MacOS_Test:
    runs-on: macos-latest
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: maven
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.4
      - name: Run Tests
        continue-on-error: true
        run: mvn clean test --file pom.xml
      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Safari_MacOS_Allure
          path: "target/allure-results/*"
      - name: Upload Execution Summary Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Safari_MacOS_Summary
          path: "target/*"
      - name: Upload Extent Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Extent_Report
          path: reports/ExtentReports/ExtentReports.html
      - name: Publish Test Results
        continue-on-error: true
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always()
        with:
            check_name: "Tests Results Safari_MacOS"
            files: |
              target/surefire-reports/TEST-*.xml
# Optional: Add additional jobs for other browsers/platforms as needed.
